include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
  # DART & FLUTTER EXCLUDES
  # Generated files
  - lib/**/*.g.dart



  # OTHER FILE EXCLUDES
  # Flutter platform support files
  - macos/**
  - windows/**
  - android/**
  - ios/**
  - web/**
  # IDE / template / build / CI related files
  - .vscode/**
  - .idea/**
  - .git/**
  - .husky/**
  - .resources/**
  - docs/**
  - .github/**
  - node_modules/**
  - build/**




# Available lints: https://dart-lang.github.io/linter/lints/index.html
# More info here:  https://dart.dev/guides/language/analysis-options
#
# Disabling a rule for a single line
# `// ignore: name_of_lint`
#
# Disabling a rule for an entire file
# `// ignore_for_file: name_of_lint`
linter:
  rules:
    library_private_types_in_public_api: false
    prefer_single_quotes: true
